name = "Adrenaserver"
author = "getchoo"
version = "1.7.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74f65a0b95433bd4724f552bc9a87d2892d9d3f8e23d441663a7bc8a3245bedf"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
