name = "Adrenaserver"
author = "getchoo"
version = "1.6.0+1.20.1.quilt"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c5cf9febcbc3c89ab98d6081d0c069aa734f210525eb0660111ef9387555435"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
